name: "Deploy Sphinx gh-pages"
on: 
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "python -m pip install --upgrade insta-tweet requests>=2.27.0"
        docs-folder: "docs/"
        
     # Create an artifact of the html output.
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: docs/build/html/

    # Publish built docs to gh-pages branch.
    # ===============================
    - name: Commit documentation changes
      run: |
        git clone https://github.com/tdkorn/insta-tweet.git --branch gh-pages --single-branch gh-pages
        cp -r docs/build/html/* gh-pages/docs/
        cd gh-pages
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
    # ===============================
